[package]
name = "photondb-engine"
version = "0.0.1"
edition = "2021"
license = "Apache-2.0"
homepage = "https://photondb.io"
repository = "https://github.com/photondb/photondb"
description = "The PhotonDB storage engine."

[dependencies]
bitflags = "1.3"
bumpalo = { version = "3.11", features = ["collections"] }
crossbeam-epoch = "0.9"
jemallocator = "0.5"
thiserror = "1.0"
log = "0.4"
env_logger = "0.9"

[dev-dependencies]
criterion = "0.3"
rand = "0.8"

[[bench]]
name = "map"
harness = false

[[bench]]
name = "stdmap"
bench = false
harness = false
